global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'magnificient-service'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: [ 'webservice-exporter:8000' ]